// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class IMasterChef024__poolInfoResult {
  value0: Address;
  value1: BigInt;
  value2: BigInt;
  value3: BigInt;
  value4: i32;
  value5: BigInt;
  value6: BigInt;

  constructor(
    value0: Address,
    value1: BigInt,
    value2: BigInt,
    value3: BigInt,
    value4: i32,
    value5: BigInt,
    value6: BigInt,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
    this.value6 = value6;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromAddress(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    map.set("value2", ethereum.Value.fromUnsignedBigInt(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    map.set(
      "value4",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value4)),
    );
    map.set("value5", ethereum.Value.fromUnsignedBigInt(this.value5));
    map.set("value6", ethereum.Value.fromUnsignedBigInt(this.value6));
    return map;
  }

  getLpToken(): Address {
    return this.value0;
  }

  getAllocPoint(): BigInt {
    return this.value1;
  }

  getLastRewardTimestamp(): BigInt {
    return this.value2;
  }

  getAccRewardTokenPerShare(): BigInt {
    return this.value3;
  }

  getDepositFeeBP(): i32 {
    return this.value4;
  }

  getHarvestInterval(): BigInt {
    return this.value5;
  }

  getTotalLp(): BigInt {
    return this.value6;
  }
}

export class IMasterChef024__userInfoResult {
  value0: BigInt;
  value1: BigInt;
  value2: BigInt;
  value3: BigInt;

  constructor(value0: BigInt, value1: BigInt, value2: BigInt, value3: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    map.set("value2", ethereum.Value.fromUnsignedBigInt(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    return map;
  }

  getAmount(): BigInt {
    return this.value0;
  }

  getRewardDebt(): BigInt {
    return this.value1;
  }

  getRewardLockedUp(): BigInt {
    return this.value2;
  }

  getNextHarvestUntil(): BigInt {
    return this.value3;
  }
}

export class IMasterChef024__poolRewardsPerSecResult {
  value0: Array<Address>;
  value1: Array<string>;
  value2: Array<BigInt>;
  value3: Array<BigInt>;

  constructor(
    value0: Array<Address>,
    value1: Array<string>,
    value2: Array<BigInt>,
    value3: Array<BigInt>,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromAddressArray(this.value0));
    map.set("value1", ethereum.Value.fromStringArray(this.value1));
    map.set("value2", ethereum.Value.fromUnsignedBigIntArray(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigIntArray(this.value3));
    return map;
  }

  getAddresses(): Array<Address> {
    return this.value0;
  }

  getSymbols(): Array<string> {
    return this.value1;
  }

  getDecimals(): Array<BigInt> {
    return this.value2;
  }

  getRewardsPerSec(): Array<BigInt> {
    return this.value3;
  }
}

export class IMasterChef024 extends ethereum.SmartContract {
  static bind(address: Address): IMasterChef024 {
    return new IMasterChef024("IMasterChef024", address);
  }

  poolInfo(param0: BigInt): IMasterChef024__poolInfoResult {
    let result = super.call(
      "poolInfo",
      "poolInfo(uint256):(address,uint256,uint256,uint256,uint16,uint256,uint256)",
      [ethereum.Value.fromUnsignedBigInt(param0)],
    );

    return new IMasterChef024__poolInfoResult(
      result[0].toAddress(),
      result[1].toBigInt(),
      result[2].toBigInt(),
      result[3].toBigInt(),
      result[4].toI32(),
      result[5].toBigInt(),
      result[6].toBigInt(),
    );
  }

  try_poolInfo(
    param0: BigInt,
  ): ethereum.CallResult<IMasterChef024__poolInfoResult> {
    let result = super.tryCall(
      "poolInfo",
      "poolInfo(uint256):(address,uint256,uint256,uint256,uint16,uint256,uint256)",
      [ethereum.Value.fromUnsignedBigInt(param0)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new IMasterChef024__poolInfoResult(
        value[0].toAddress(),
        value[1].toBigInt(),
        value[2].toBigInt(),
        value[3].toBigInt(),
        value[4].toI32(),
        value[5].toBigInt(),
        value[6].toBigInt(),
      ),
    );
  }

  userInfo(param0: BigInt, param1: Address): IMasterChef024__userInfoResult {
    let result = super.call(
      "userInfo",
      "userInfo(uint256,address):(uint256,uint256,uint256,uint256)",
      [
        ethereum.Value.fromUnsignedBigInt(param0),
        ethereum.Value.fromAddress(param1),
      ],
    );

    return new IMasterChef024__userInfoResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
      result[2].toBigInt(),
      result[3].toBigInt(),
    );
  }

  try_userInfo(
    param0: BigInt,
    param1: Address,
  ): ethereum.CallResult<IMasterChef024__userInfoResult> {
    let result = super.tryCall(
      "userInfo",
      "userInfo(uint256,address):(uint256,uint256,uint256,uint256)",
      [
        ethereum.Value.fromUnsignedBigInt(param0),
        ethereum.Value.fromAddress(param1),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new IMasterChef024__userInfoResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
        value[2].toBigInt(),
        value[3].toBigInt(),
      ),
    );
  }

  totalAllocPoint(): BigInt {
    let result = super.call(
      "totalAllocPoint",
      "totalAllocPoint():(uint256)",
      [],
    );

    return result[0].toBigInt();
  }

  try_totalAllocPoint(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "totalAllocPoint",
      "totalAllocPoint():(uint256)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  poolRewarders(_pid: BigInt): Array<Address> {
    let result = super.call(
      "poolRewarders",
      "poolRewarders(uint256):(address[])",
      [ethereum.Value.fromUnsignedBigInt(_pid)],
    );

    return result[0].toAddressArray();
  }

  try_poolRewarders(_pid: BigInt): ethereum.CallResult<Array<Address>> {
    let result = super.tryCall(
      "poolRewarders",
      "poolRewarders(uint256):(address[])",
      [ethereum.Value.fromUnsignedBigInt(_pid)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddressArray());
  }

  poolRewardsPerSec(_pid: BigInt): IMasterChef024__poolRewardsPerSecResult {
    let result = super.call(
      "poolRewardsPerSec",
      "poolRewardsPerSec(uint256):(address[],string[],uint256[],uint256[])",
      [ethereum.Value.fromUnsignedBigInt(_pid)],
    );

    return new IMasterChef024__poolRewardsPerSecResult(
      result[0].toAddressArray(),
      result[1].toStringArray(),
      result[2].toBigIntArray(),
      result[3].toBigIntArray(),
    );
  }

  try_poolRewardsPerSec(
    _pid: BigInt,
  ): ethereum.CallResult<IMasterChef024__poolRewardsPerSecResult> {
    let result = super.tryCall(
      "poolRewardsPerSec",
      "poolRewardsPerSec(uint256):(address[],string[],uint256[],uint256[])",
      [ethereum.Value.fromUnsignedBigInt(_pid)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new IMasterChef024__poolRewardsPerSecResult(
        value[0].toAddressArray(),
        value[1].toStringArray(),
        value[2].toBigIntArray(),
        value[3].toBigIntArray(),
      ),
    );
  }
}

export class DepositCall extends ethereum.Call {
  get inputs(): DepositCall__Inputs {
    return new DepositCall__Inputs(this);
  }

  get outputs(): DepositCall__Outputs {
    return new DepositCall__Outputs(this);
  }
}

export class DepositCall__Inputs {
  _call: DepositCall;

  constructor(call: DepositCall) {
    this._call = call;
  }

  get _pid(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get _amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class DepositCall__Outputs {
  _call: DepositCall;

  constructor(call: DepositCall) {
    this._call = call;
  }
}

export class WithdrawCall extends ethereum.Call {
  get inputs(): WithdrawCall__Inputs {
    return new WithdrawCall__Inputs(this);
  }

  get outputs(): WithdrawCall__Outputs {
    return new WithdrawCall__Outputs(this);
  }
}

export class WithdrawCall__Inputs {
  _call: WithdrawCall;

  constructor(call: WithdrawCall) {
    this._call = call;
  }

  get _pid(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get _amount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class WithdrawCall__Outputs {
  _call: WithdrawCall;

  constructor(call: WithdrawCall) {
    this._call = call;
  }
}
