// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext,
} from "@graphprotocol/graph-ts";

export class Pair extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Pair", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("Pair", [address.toHex()], context);
  }
}

export class Collateral extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Collateral", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "Collateral",
      [address.toHex()],
      context,
    );
  }
}

export class Borrowable extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Borrowable", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "Borrowable",
      [address.toHex()],
      context,
    );
  }
}

export class FarmingPool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("FarmingPool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "FarmingPool",
      [address.toHex()],
      context,
    );
  }
}

export class StakedLPToken extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("StakedLPToken", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "StakedLPToken",
      [address.toHex()],
      context,
    );
  }
}
